### ISSUE TITLE
Example: Bounding box calculation produces some unexpected results

### ISSUE THREAD

**Issue by joeyklee** [sztanko/maximum_width_rectangle#2]
On “click” you can get back the angle of the feature as well as create the bounding box of the feature as calculated by the getRect() function. Sometimes the bounding box of the feature comes up with some unexpected results:
![screen shot 2015-01-14 at 11 54 35 am](https://cloud.githubusercontent.com/assets/3622055/5747285/c649e894-9beb-11e4-864f-3dafabcb611f.png)

**Comment by sztanko** [comment]
Hi Joey, thanks for noticing it!

Could you please send me the geojson of those buildings that produce weird results?
Did you apply any projection transformations before calculating the bb?

Sorry for delay,

Dimi.

**Comment by joeyklee** [comment]
Hi Dimi,
Sure thing:

> Did you apply any projection transformations before calculating the bb?
- mm not that I can remember. The projection is the wgs84, epsg 4236

Hope this helps!

Best,
J

**Comment by sztanko** [comment]
Thank Joey!

I will need to double check it, but it might happen that the rectangles are in fact good, it is just projections that distorts them. I need to check it however. In any case, I will need to find a solution that makes this rectangle thing working correctly in spherical coordinates like our earth:)

**Comment by joeyklee** [comment]
Hi Dimi,

Sure thing! This is all super cool. Happy to help in whatever way I can!

Best,
J

**Comment by b-g** [comment]
Hi all, maybe it is just the direction of the y / lat axis? I guess the algo works in y-axis down, whereas we need y-axis up ... Best, B
